# Generated by Django 5.1.1 on 2024-09-24 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalArea',
            fields=[
                ('local_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_area_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.district')),
                ('local_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nisapp.localarea')),
            ],
        ),
    ]
