# Generated by Django 5.1.1 on 2024-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localarea',
            name='local_area_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
