# Generated by Django 5.1.1 on 2024-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0002_alter_district_district_id_alter_lead_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
